# Generated by Django 4.2.5 on 2023-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view_count',
            new_name='views_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
    ]
